trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
- stage: Hello
  displayName: Hello there
  jobs:
  - job: greeting
    displayName: Say hello
    steps:
    - script: |
        echo 'hello allegro'
        echo ':)'
      displayName: 'say hello to your future employer'

- stage: BuildAndTest
  displayName: 'Build and test web-api services'
  jobs:
  - job: Service1
    displayName: 'Run and test Service1'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Service1/Wiktor.Kisielewski.Service1'
        testRunTitle: 'Running Service 1'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Service1/Wiktor.Kisielewski.Service1.Tests'
        testRunTitle: 'Testing Service 1'

  - job: Service2
    displayName: 'Run and test Service2'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Service2/Wiktor.Kisielewski.Service2'
        testRunTitle: 'Running Service 2'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Service2/Wiktor.Kisielewski.Service2.Tests'
        testRunTitle: 'Testing Service 2'

  - job: Service3
    displayName: 'Run and test Service3'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Service3/Wiktor.Kisielewski.Service3'
        testRunTitle: 'Running Service 3'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Service3/Wiktor.Kisielewski.Service3.Tests'
        testRunTitle: 'Testing Service 3'

- stage: DockerImages
  displayName: Build docker images
  jobs:
  - job: 'DockerizeService1'
    displayName: 'Build and push docker image for Service1'
    steps:
    - task: Docker@2
      displayName: 'Build and push Service1'
      inputs:
        containerRegistry: 'docker_hub'
        repository: 'wiktorkisielewski/allegro_special'        
        command: 'buildAndPush'
        Dockerfile: 'Service1/Wiktor.Kisielewski.Service1/Dockerfile'
        tags: Service1_$(Build.BuildId)
  - job: 'DockerizeService2'
    displayName: 'Build and push docker image for Service2'
    steps:
    - task: Docker@2
      displayName: 'Build and push Service2'
      inputs:
        containerRegistry: 'docker_hub'
        repository: 'wiktorkisielewski/allegro_special'        
        command: 'buildAndPush'
        Dockerfile: 'Service2/Wiktor.Kisielewski.Service2/Dockerfile'
        tags: Service2_$(Build.BuildId)
  - job: 'DockerizeService3'
    displayName: 'Build and push docker image for Service3'
    steps:
    - task: Docker@2
      displayName: 'Build and push Service3'
      inputs:
        containerRegistry: 'docker_hub'
        repository: 'wiktorkisielewski/allegro_special'        
        command: 'buildAndPush'
        Dockerfile: 'Service3/Wiktor.Kisielewski.Service3/Dockerfile'
        tags: Service3_$(Build.BuildId)
